services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: eratani
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow", "-d", "eratani"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow-db-init:
    image: apache/airflow:2.7.1-python3.10
    #build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/eratani
      #AIRFLOW_UID: 50000
      #AIRFLOW_GID: 0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
    command: ["airflow", "db", "migrate"] # PERINTAH DB MIGRATE LANGSUNG

  # LAYANAN INI HANYA UNTUK MEMBUAT USER
  airflow-users-init: # LAYANAN BARU UNTUK USER
    image: apache/airflow:2.7.1-python3.10
    #build: .
    depends_on:
      airflow-db-init: # Bergantung pada DB update yang berhasil
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/eratani
      #AIRFLOW_UID: 50000
      #AIRFLOW_GID: 0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
    command: [
      "airflow", "users", "create",
      "--username", "admin",
      "--password", "admin",
      "--firstname", "Admin",
      "--lastname", "User",
      "--role", "Admin",
      "--email", "admin@example.com"
    ]

  airflow-webserver:
    image: apache/airflow:2.7.1-python3.10
    #build: .
    depends_on:
      airflow-users-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/eratani
      AIRFLOW__WEBSERVER__SECRET_KEY: mysecret
      #AIRFLOW_UID: 50000
      #AIRFLOW_GID: 0
      AIRFLOW__WEBSERVER__WORKERS: 1
      AIRFLOW__WEBSERVER__WEB_SERVER_HOST: 0.0.0.0
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__LOGGING__LOGGING_LEVEL: DEBUG
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
    command: webserver #["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "1", "airflow.www.gunicorn_config"]

  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.10
    #build: .
    depends_on:
      airflow-users-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/eratani
      #AIRFLOW_UID: 50000
      #AIRFLOW_GID: 0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config
    command: scheduler

volumes:
  postgres_data:
